const {createClient}=window.supabase;
const client=createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY);
const $=id=>document.getElementById(id);let me=null,conversations=[],members={},active=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function memberLabel(id){return members[id]?.display_name||'Member';}
function renderMembers(filter=''){const box=$('memberItems'),q=filter.toLowerCase();const rows=conversations.filter(c=>memberLabel(c.subscriber_id).toLowerCase().includes(q));box.innerHTML=rows.length?rows.map(c=>{const p=members[c.subscriber_id]||{};return `<button class="member-item ${active===c.id?'active':''}" data-id="${c.id}"><strong>${esc(p.display_name||'Member')}</strong><small>${esc(p.subscription_status||'inactive')} • ${p.age_verified?'age verified':'18+ self-confirmed'}</small><span class="admin-meta"><span class="admin-chip">${new Date(c.created_at).toLocaleDateString()}</span></span></button>`;}).join(''):'<div class="empty-chat" style="padding:35px 10px">No members yet.</div>';box.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openConversation(b.dataset.id));}
async function loadMessages(){if(!active)return;const {data,error}=await client.from('messages').select('*').eq('conversation_id',active).order('created_at',{ascending:true});if(error){$('adminStatus').textContent=error.message;return;}const b=$('adminMessages');b.innerHTML=data?.length?data.map(m=>`<div class="message ${m.sender_id===me.id?'mine':'theirs'}"><div>${esc(m.body||'')}</div><small>${new Date(m.created_at).toLocaleString()}</small></div>`).join(''):'<div class="empty-chat">No messages yet.</div>';b.scrollTop=b.scrollHeight;}
async function openConversation(id){active=id;renderMembers($('memberSearch').value);const c=conversations.find(x=>x.id===id),p=members[c.subscriber_id]||{};$('chatMember').textContent=p.display_name||'Member';$('chatMeta').textContent=(p.subscription_status||'inactive')+' • '+(p.age_verified?'verified':'not verified');$('adminMessageInput').disabled=false;$('adminSend').disabled=false;await loadMessages();}
async function boot(){const {data:{session}}=await client.auth.getSession();if(!session){location.href='developer.html';return;}const p=await client.from('profiles').select('*').eq('id',session.user.id).single();if(p.error||p.data?.role!=='admin'){location.href='developer.html';return;}me=p.data;const c=await client.from('conversations').select('*').order('created_at',{ascending:false});if(c.error){$('adminStatus').textContent=c.error.message;return;}conversations=c.data||[];const ids=[...new Set(conversations.map(x=>x.subscriber_id))];if(ids.length){const r=await client.from('profiles').select('id,display_name,subscription_status,age_verified').in('id',ids);(r.data||[]).forEach(x=>members[x.id]=x);}renderMembers();$('adminStatus').textContent=conversations.length?`${conversations.length} private conversation${conversations.length===1?'':'s'}`:'No member conversations yet.';client.channel('creator-inbox').on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},()=>{if(active)loadMessages();}).subscribe();}
$('memberSearch').addEventListener('input',e=>renderMembers(e.target.value));
$('adminMessageForm').addEventListener('submit',async e=>{e.preventDefault();if(!active)return;const input=$('adminMessageInput'),body=input.value.trim();if(!body)return;const r=await client.from('messages').insert({conversation_id:active,sender_id:me.id,body});if(r.error){$('adminStatus').textContent=r.error.message;return;}input.value='';await loadMessages();});
$('adminLogout').onclick=async()=>{await client.auth.signOut();location.href='index.html';};boot();