const { createClient } = window.supabase;
const client=createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY);
const $=id=>document.getElementById(id);let profile=null,conversationId=null;
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function render(rows){const b=$('messages');if(!rows?.length){b.innerHTML='<div class="empty-chat">No messages yet. Say hi 💗</div>';return;}b.innerHTML=rows.map(m=>'<div class="message '+(m.sender_id===profile.id?'mine':'theirs')+'"><div>'+esc(m.body||'')+'</div><small>'+new Date(m.created_at).toLocaleString()+'</small></div>').join('');b.scrollTop=b.scrollHeight;}
async function load(){const {data,error}=await client.from('messages').select('*').eq('conversation_id',conversationId).order('created_at',{ascending:true});if(!error)render(data);}
async function boot(){const {data:{session}}=await client.auth.getSession();if(!session){location.href='index.html';return;}const p=await client.from('profiles').select('*').eq('id',session.user.id).single();if(p.error){$('status').textContent=p.error.message;return;}profile=p.data;$('displayName').textContent=profile.display_name||'Member';const topics=Array.isArray(profile.topic_preferences)?profile.topic_preferences:[];document.querySelectorAll('.topic-grid input').forEach(i=>i.checked=topics.includes(i.value));let c=await client.from('conversations').select('id').eq('subscriber_id',profile.id).maybeSingle();if(c.error){$('status').textContent=c.error.message;return;}if(!c.data){c=await client.from('conversations').insert({subscriber_id:profile.id}).select('id').single();if(c.error){$('status').textContent=c.error.message;return;}}conversationId=c.data.id;$('status').textContent='Your private conversation is ready.';await load();client.channel('chat-'+conversationId).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:'conversation_id=eq.'+conversationId},load).subscribe();}
$('saveTopics').onclick=async()=>{const topic_preferences=[...document.querySelectorAll('.topic-grid input:checked')].map(i=>i.value);const r=await client.from('profiles').update({topic_preferences}).eq('id',profile.id);$('topicSaved').textContent=r.error?' '+r.error.message:' Saved ✓';setTimeout(()=>$('topicSaved').textContent='',1800);};
$('messageForm').addEventListener('submit',async e=>{e.preventDefault();const input=$('messageInput'),body=input.value.trim();if(!body)return;const r=await client.from('messages').insert({conversation_id:conversationId,sender_id:profile.id,body});if(r.error){$('status').textContent=r.error.message;return;}input.value='';await load();});
$('logout').onclick=async()=>{await client.auth.signOut();location.href='index.html';};boot();