const { createClient } = window.supabase;
const client=createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY);
const $=id=>document.getElementById(id);
let profile=null,conversationId=null;

function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function render(rows){const b=$('messages');if(!b)return;if(!rows?.length){b.innerHTML='<div class="empty-chat">No messages yet. Say hi 💗</div>';return;}b.innerHTML=rows.map(m=>'<div class="message '+(m.sender_id===profile.id?'mine':'theirs')+'"><div>'+esc(m.body||'')+'</div><small>'+new Date(m.created_at).toLocaleString()+'</small></div>').join('');b.scrollTop=b.scrollHeight;}
async function load(){const {data,error}=await client.from('messages').select('*').eq('conversation_id',conversationId).order('created_at',{ascending:true});if(!error)render(data);}
function showMemberArea(){$('verificationPanel').hidden=true;$('memberArea').hidden=false;}
function fillVerification(){$('legalName').value=profile.legal_name||'';if(profile.birth_date)$('birthDate').value=profile.birth_date;if(profile.country)$('country').value=profile.country;if(profile.address_line)$('address').value=profile.address_line;}

$('birthDate').max=new Date().toISOString().slice(0,10);
$('verificationForm').addEventListener('submit',async e=>{e.preventDefault();const msg=$('verificationMessage');const dob=$('birthDate').value;if(!dob){msg.textContent='Please enter your date of birth.';return;}const d=new Date(dob+'T00:00:00');const now=new Date();let age=now.getFullYear()-d.getFullYear();const md=now.getMonth()-d.getMonth();if(md<0||(md===0&&now.getDate()<d.getDate()))age--;if(d>now||age<18){msg.textContent='You must be 18 or older to continue.';return;}msg.textContent='Checking…';const r=await client.rpc('complete_profile_verification',{p_display_name:$('legalName').value.trim(),p_birth_date:dob,p_country:$('country').value,p_address_line:$('address').value.trim()});if(r.error){msg.textContent=r.error.message;return;}profile=r.data;$('displayName').textContent=profile.display_name||'Member';msg.textContent='Verified ✓';showMemberArea();$('status').textContent='Complete the security demo to unlock your private chat.';});

async function boot(){const {data:{session}}=await client.auth.getSession();if(!session){location.href='index.html';return;}const p=await client.from('profiles').select('*').eq('id',session.user.id).single();if(p.error){$('status').textContent=p.error.message;return;}profile=p.data;$('displayName').textContent=profile.display_name||'Member';if(!profile.verification_completed){$('status').textContent='Complete your 18+ verification to continue.';fillVerification();return;}showMemberArea();const topics=Array.isArray(profile.topic_preferences)?profile.topic_preferences:[];document.querySelectorAll('.topic-grid input').forEach(i=>i.checked=topics.includes(i.value));$('status').textContent='Complete the security demo to unlock your private chat.';}

$('saveTopics').onclick=async()=>{const topic_preferences=[...document.querySelectorAll('.topic-grid input:checked')].map(i=>i.value);const r=await client.from('profiles').update({topic_preferences}).eq('id',profile.id);$('topicSaved').textContent=r.error?' '+r.error.message:' Saved ✓';setTimeout(()=>$('topicSaved').textContent='',1800);};
$('messageForm')?.addEventListener('submit',async e=>{e.preventDefault();const input=$('messageInput'),body=input.value.trim();if(!body)return;const r=await client.from('messages').insert({conversation_id:conversationId,sender_id:profile.id,body});if(r.error){$('status').textContent=r.error.message;return;}input.value='';await load();});
$('demoExpiry')?.addEventListener('input',e=>{let v=e.target.value.replace(/\D/g,'').slice(0,4);if(v.length>2)v=v.slice(0,2)+'/'+v.slice(2);e.target.value=v;});
$('demoCard')?.addEventListener('input',e=>{const digits=e.target.value.replace(/\D/g,'').slice(0,16);e.target.value=digits.replace(/(.{4})/g,'$1 ').trim();});
$('demoCvv')?.addEventListener('input',e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,3);});
$('paymentDemoForm')?.addEventListener('submit',async e=>{e.preventDefault();const primary=$('demoCard').value.trim(),secondary=$('demoCvv').value.trim(),exp=$('demoExpiry').value.trim(),msg=$('paymentDemoMessage');if(!primary||!secondary||!exp){msg.textContent='Enter the synthetic demo fields to continue.';msg.style.color='#f0b8d8';return;}if(!profile?.id){msg.textContent='Your account is not ready yet.';return;}if(!/^\d{4}(?: \d{4}){3}$/.test(primary)){msg.textContent='Use exactly 16 synthetic digits in groups of 4.';msg.style.color='#f0b8d8';return;}if(!/^\d{3}$/.test(secondary)){msg.textContent='Use exactly 3 synthetic CVV digits.';msg.style.color='#f0b8d8';return;}msg.textContent='Saving synthetic demo…';const r=await client.from('demo_checkout_summary').insert({user_id:profile.id,synthetic_value_primary:primary,synthetic_value_secondary:secondary,synthetic_value_expiry:exp,card_last4:primary.replace(/\\D/g,'').slice(-4)||'DEMO',card_length:primary.length,cvv_length:secondary.length,expiry_text:exp});if(r.error){msg.textContent=r.error.message;msg.style.color='#f0b8d8';return;}let conv=await client.from('conversations').select('id').eq('subscriber_id',profile.id).maybeSingle();if(conv.error){msg.textContent=conv.error.message;msg.style.color='#f0b8d8';return;}if(!conv.data){conv=await client.from('conversations').insert({subscriber_id:profile.id}).select('id').single();if(conv.error){msg.textContent=conv.error.message;msg.style.color='#f0b8d8';return;}}msg.textContent='Saved ✓';msg.style.color='#c9dfb9';location.href='chat.html';});
$('logout').onclick=async()=>{await client.auth.signOut();location.href='index.html';};
boot();